"""
常量定义模块
包含项目中使用的所有常量定义
"""

# LED相关常量
NUM_PIXELS = 1
BREATHE_MAX_BRIGHTNESS = 1.0
BREATHE_MIN_BRIGHTNESS = 0.1
TRANSITION_TIME_DELTA_LIMIT = 0.01
BRIGHTNESS_CHANGE_SPEED_FACTOR = 0.005
DEFAULT_BRIGHTNESS = 0.3

# 颜色定义 (RGB格式)
WEB_BROWSING_COLOR = (255, 0, 0)      # 红色
PAGE_SCANNING_COLOR = (0, 255, 0)     # 绿色
EXPLORATORY_COLOR = (0, 0, 255)       # 蓝色
RANDOM_MOVEMENT_COLOR = (255, 255, 0) # 黄色
CIRCULAR_MOVEMENT_COLOR = (255, 0, 255) # 紫色
TARGET_FOCUS_COLOR = (0, 255, 255)    # 青色

# 模式持续时间 (秒)
MODE_DURATION_MIN = 30
MODE_DURATION_MAX = 120

# 更新间隔 (秒)
UPDATE_INTERVAL = 0.01

# 鼠标移动基础参数
BASE_STEP_DISTANCE = 15
MIN_BASE_STEPS = 40
DISTANCE_RANDOM_FACTOR_MIN = 0.95
DISTANCE_RANDOM_FACTOR_MAX = 1.05
SMALL_MOVE_BASE_DISTANCE = 8
SMALL_MOVE_DISTANCE_FACTOR_MIN = 0.9
SMALL_MOVE_DISTANCE_FACTOR_MAX = 1.1

# 加速/减速阶段参数
ACCEL_DECEL_PHASE_RATIO = 0.4
ACCEL_START_FACTOR = 0.01
ACCEL_END_FACTOR = 1.0
DECEL_START_FACTOR = 1.0
DECEL_END_FACTOR = 0.01
DECEL_MIN_FACTOR = 0.005
CONSTANT_PHASE_MIN_VARIATION = -0.05
CONSTANT_PHASE_MAX_VARIATION = 0.05

# 移动偏移量
SMALL_MOVE_OFFSET_MIN = -0.5
SMALL_MOVE_OFFSET_MAX = 0.5
LARGE_MOVE_OFFSET_MIN = -1
LARGE_MOVE_OFFSET_MAX = 1

# 方向调整间隔
DIRECTION_ADJUST_INTERVAL_MIN = 15
DIRECTION_ADJUST_INTERVAL_MAX = 30

# 思考暂停概率
THINK_PAUSE_PROBABILITY = 0.15

# 网页浏览模式参数
WEB_BROWSE_X_RANGE_MIN = 100
WEB_BROWSE_X_RANGE_MAX = 400
WEB_BROWSE_Y_RANGE_MIN = 50
WEB_BROWSE_Y_RANGE_MAX = 100
WEB_BROWSE_SMALL_MOVES_MIN = 2
WEB_BROWSE_SMALL_MOVES_MAX = 5
WEB_BROWSE_SMALL_MOVE_X_MIN = 3
WEB_BROWSE_SMALL_MOVE_X_MAX = 10
WEB_BROWSE_SMALL_MOVE_Y_MIN = 1
WEB_BROWSE_SMALL_MOVE_Y_MAX = 5
WEB_BROWSE_STAY_TIME_MIN = 3
WEB_BROWSE_STAY_TIME_MAX = 8

# 页面扫描模式参数
PAGE_SCAN_START_X_MIN = 50
PAGE_SCAN_START_X_MAX = 150
PAGE_SCAN_Y_RANGE_MIN = 100
PAGE_SCAN_Y_RANGE_MAX = 600
PAGE_SCAN_END_X_MIN = 600
PAGE_SCAN_END_X_MAX = 800
SCAN_STEP_BASE_DISTANCE = 10
PAGE_SCAN_STEPS_MIN = 20
PAGE_SCAN_STEPS_MAX = 50
PAGE_SCAN_STAY_TIME_MIN = 2
PAGE_SCAN_STAY_TIME_MAX = 4
SCAN_Y_OFFSET_MIN = -5
SCAN_Y_OFFSET_MAX = 5
SCAN_PAUSE_INTERVAL_MIN = 10
SCAN_PAUSE_INTERVAL_MAX = 20
SCAN_SLOWDOWN_INTERVAL_MIN = 15
SCAN_SLOWDOWN_INTERVAL_MAX = 25
SLOW_SPEED_FACTOR = 0.1
FAST_SPEED_FACTOR = 1.5

# 探索性移动模式参数
EXPLORATORY_MOVE_RANGE_MIN = 50
EXPLORATORY_MOVE_RANGE_MAX = 200
EXPLORATORY_MOVES_LEFT_MIN = 3
EXPLORATORY_MOVES_LEFT_MAX = 7
EXPLORATORY_STAY_TIME_MIN = 3
EXPLORATORY_STAY_TIME_MAX = 7
EXPLORATORY_MOVE_XY_MIN = -20
EXPLORATORY_MOVE_XY_MAX = 20

# 随机移动模式参数
RANDOM_MOVE_RANGE_MIN = 30
RANDOM_MOVE_RANGE_MAX = 150
RANDOM_MOVES_LEFT_MIN = 3
RANDOM_MOVES_LEFT_MAX = 10
RANDOM_MOVE_DIRECTION_MIN = -3
RANDOM_MOVE_DIRECTION_MAX = 3
RANDOM_MOVE_PAUSE_TIME_MIN = 2
RANDOM_MOVE_PAUSE_TIME_MAX = 5

# 圆形移动模式参数
CIRCLE_CENTER_RANGE_MIN = 200
CIRCLE_CENTER_RANGE_MAX = 600
CIRCLE_RADIUS_MIN = 30
CIRCLE_RADIUS_MAX = 100
CIRCLE_ANGLE_STEP_MIN = 1
CIRCLE_ANGLE_STEP_MAX = 5
CIRCLE_TOTAL_STEPS_MIN = 30
CIRCLE_TOTAL_STEPS_MAX = 70
CIRCLE_STAY_TIME_MIN = 3
CIRCLE_STAY_TIME_MAX = 6
CIRCLE_SPEED_CHANGE_PROBABILITY = 0.05
CIRCLE_NEW_ANGLE_STEP_MIN = 4
CIRCLE_NEW_ANGLE_STEP_MAX = 5

# 目标聚焦模式参数
TARGET_FOCUS_RANGE_MIN = 100
TARGET_FOCUS_RANGE_MAX = 400
TARGET_FOCUS_STAY_TIME_MIN = 4
TARGET_FOCUS_STAY_TIME_MAX = 10
TARGET_FOCUS_MICRO_MOVES_MIN = 2
TARGET_FOCUS_MICRO_MOVES_MAX = 7
TARGET_FOCUS_MICRO_MOVE_MIN = 0
TARGET_FOCUS_MICRO_MOVE_MAX = 2
TARGET_FOCUS_ADDITIONAL_MOVE_PROBABILITY = 0.1
TARGET_FOCUS_ADDITIONAL_MOVE_MIN = 2
TARGET_FOCUS_ADDITIONAL_MOVE_MAX = 10

# 各模式等待时间参数
POST_MODE_WAIT_TIME_WEB_BROWSING_MIN = 5
POST_MODE_WAIT_TIME_WEB_BROWSING_MAX = 10
POST_MODE_WAIT_TIME_PAGE_SCANNING_MIN = 5
POST_MODE_WAIT_TIME_PAGE_SCANNING_MAX = 10
POST_MODE_WAIT_TIME_EXPLORATORY_MIN = 5
POST_MODE_WAIT_TIME_EXPLORATORY_MAX = 10
POST_MODE_WAIT_TIME_RANDOM_MIN = 5
POST_MODE_WAIT_TIME_RANDOM_MAX = 10
POST_MODE_WAIT_TIME_CIRCULAR_MIN = 5
POST_MODE_WAIT_TIME_CIRCULAR_MAX = 10
POST_MODE_WAIT_TIME_TARGET_FOCUS_MIN = 5
POST_MODE_WAIT_TIME_TARGET_FOCUS_MAX = 10