"""
常量定义模块
包含项目中使用的所有常量定义

组织结构：
1. LED 相关常量（颜色、亮度）
2. 模式和更新参数
3. 鼠标移动基础参数
4. 各模式专用参数（网页浏览、页面扫描、探索移动等）
5. 算法参数（贝塞尔、Perlin、风力、重力）
"""

# LED相关常量
NUM_PIXELS = 1
BREATHE_MAX_BRIGHTNESS = 1.0
BREATHE_MIN_BRIGHTNESS = 0.1
TRANSITION_TIME_DELTA_LIMIT = 0.01
BRIGHTNESS_CHANGE_SPEED_FACTOR = 0.005
DEFAULT_BRIGHTNESS = 0.3

# 颜色定义 (RGB格式)
WEB_BROWSING_COLOR = (255, 0, 0)      # 红色
PAGE_SCANNING_COLOR = (0, 255, 0)     # 绿色
EXPLORATORY_COLOR = (0, 0, 255)       # 蓝色
RANDOM_MOVEMENT_COLOR = (255, 255, 0) # 黄色
CIRCULAR_MOVEMENT_COLOR = (255, 0, 255) # 紫色
TARGET_FOCUS_COLOR = (0, 255, 255)    # 青色

# 模式持续时间 (秒)
MODE_DURATION_MIN = 60
MODE_DURATION_MAX = 300

# 更新间隔 (秒)
# 匹配 CircuitPython 默认 USB HID 回报率 125Hz
UPDATE_INTERVAL = 0.008  # 8ms = 125Hz

# 鼠标移动基础参数
BASE_STEP_DISTANCE = 15
MIN_BASE_STEPS = 40
DISTANCE_RANDOM_FACTOR_MIN = 0.95
DISTANCE_RANDOM_FACTOR_MAX = 1.05
SMALL_MOVE_BASE_DISTANCE = 8
SMALL_MOVE_DISTANCE_FACTOR_MIN = 0.9
SMALL_MOVE_DISTANCE_FACTOR_MAX = 1.1

# 加速/减速阶段参数
ACCEL_DECEL_PHASE_RATIO = 40
ACCEL_START_FACTOR = 1
ACCEL_END_FACTOR = 100
DECEL_START_FACTOR = 100
DECEL_END_FACTOR = 1
DECEL_MIN_FACTOR = 1
CONSTANT_PHASE_MIN_VARIATION = -5
CONSTANT_PHASE_MAX_VARIATION = 5

# 移动偏移量
SMALL_MOVE_OFFSET_MIN = -50
SMALL_MOVE_OFFSET_MAX = 50
LARGE_MOVE_OFFSET_MIN = -100
LARGE_MOVE_OFFSET_MAX = 100

# 方向调整间隔
DIRECTION_ADJUST_INTERVAL_MIN = 15
DIRECTION_ADJUST_INTERVAL_MAX = 30

# 思考暂停概率
THINK_PAUSE_PROBABILITY = 15

# 网页浏览模式参数（特点：中等范围，多次小幅移动）
WEB_BROWSE_X_RANGE_MIN = 150
WEB_BROWSE_X_RANGE_MAX = 500
WEB_BROWSE_Y_RANGE_MIN = 80
WEB_BROWSE_Y_RANGE_MAX = 200
WEB_BROWSE_SMALL_MOVES_MIN = 3
WEB_BROWSE_SMALL_MOVES_MAX = 8
WEB_BROWSE_SMALL_MOVE_X_MIN = 3
WEB_BROWSE_SMALL_MOVE_X_MAX = 10
WEB_BROWSE_SMALL_MOVE_Y_MIN = 1
WEB_BROWSE_SMALL_MOVE_Y_MAX = 5
WEB_BROWSE_STAY_TIME_MIN = 3
WEB_BROWSE_STAY_TIME_MAX = 8

# 页面扫描模式参数
PAGE_SCAN_START_X_MIN = 50
PAGE_SCAN_START_X_MAX = 150
PAGE_SCAN_Y_RANGE_MIN = 100
PAGE_SCAN_Y_RANGE_MAX = 600
PAGE_SCAN_END_X_MIN = 600
PAGE_SCAN_END_X_MAX = 800
SCAN_STEP_BASE_DISTANCE = 20
PAGE_SCAN_STEPS_MIN = 15
PAGE_SCAN_STEPS_MAX = 40
PAGE_SCAN_STAY_TIME_MIN = 2
PAGE_SCAN_STAY_TIME_MAX = 4
SCAN_Y_OFFSET_MIN = -5
SCAN_Y_OFFSET_MAX = 5
SCAN_PAUSE_INTERVAL_MIN = 10
SCAN_PAUSE_INTERVAL_MAX = 20
SCAN_SLOWDOWN_INTERVAL_MIN = 15
SCAN_SLOWDOWN_INTERVAL_MAX = 25
SLOW_SPEED_FACTOR = 10
FAST_SPEED_FACTOR = 150

# 探索性移动模式参数
EXPLORATORY_MOVE_RANGE_MIN = 100
EXPLORATORY_MOVE_RANGE_MAX = 600
EXPLORATORY_MOVES_LEFT_MIN = 3
EXPLORATORY_MOVES_LEFT_MAX = 7
EXPLORATORY_STAY_TIME_MIN = 3
EXPLORATORY_STAY_TIME_MAX = 7
EXPLORATORY_MOVE_XY_MIN = -20
EXPLORATORY_MOVE_XY_MAX = 20

# 随机移动模式参数
RANDOM_MOVE_RANGE_MIN = 100
RANDOM_MOVE_RANGE_MAX = 500
RANDOM_MOVES_LEFT_MIN = 3
RANDOM_MOVES_LEFT_MAX = 10
RANDOM_MOVE_DIRECTION_MIN = -3
RANDOM_MOVE_DIRECTION_MAX = 3
RANDOM_MOVE_PAUSE_TIME_MIN = 2
RANDOM_MOVE_PAUSE_TIME_MAX = 5

# 圆形移动模式参数（特点：大半径圆形轨迹）
CIRCLE_CENTER_RANGE_MIN = 300
CIRCLE_CENTER_RANGE_MAX = 500
CIRCLE_RADIUS_MIN = 50
CIRCLE_RADIUS_MAX = 150
CIRCLE_ANGLE_STEP_MIN = 10
CIRCLE_ANGLE_STEP_MAX = 40
CIRCLE_TOTAL_STEPS_MIN = 60
CIRCLE_TOTAL_STEPS_MAX = 120
CIRCLE_STAY_TIME_MIN = 3
CIRCLE_STAY_TIME_MAX = 6
CIRCLE_SPEED_CHANGE_PROBABILITY = 5
CIRCLE_NEW_ANGLE_STEP_MIN = 10
CIRCLE_NEW_ANGLE_STEP_MAX = 50

# 目标聚焦模式参数（特点：小范围，频繁微调）
TARGET_FOCUS_RANGE_MIN = 50
TARGET_FOCUS_RANGE_MAX = 200
TARGET_FOCUS_STAY_TIME_MIN = 4
TARGET_FOCUS_STAY_TIME_MAX = 10
TARGET_FOCUS_MICRO_MOVES_MIN = 1
TARGET_FOCUS_MICRO_MOVES_MAX = 5
TARGET_FOCUS_MICRO_MOVE_MIN = 0
TARGET_FOCUS_MICRO_MOVE_MAX = 2
TARGET_FOCUS_ADDITIONAL_MOVE_PROBABILITY = 0.1
TARGET_FOCUS_ADDITIONAL_MOVE_MIN = 2
TARGET_FOCUS_ADDITIONAL_MOVE_MAX = 10

# 各模式等待时间参数
POST_MODE_WAIT_TIME_WEB_BROWSING_MIN = 5
POST_MODE_WAIT_TIME_WEB_BROWSING_MAX = 10
POST_MODE_WAIT_TIME_PAGE_SCANNING_MIN = 5
POST_MODE_WAIT_TIME_PAGE_SCANNING_MAX = 10
POST_MODE_WAIT_TIME_EXPLORATORY_MIN = 5
POST_MODE_WAIT_TIME_EXPLORATORY_MAX = 10
POST_MODE_WAIT_TIME_RANDOM_MIN = 5
POST_MODE_WAIT_TIME_RANDOM_MAX = 10
POST_MODE_WAIT_TIME_CIRCULAR_MIN = 5
POST_MODE_WAIT_TIME_CIRCULAR_MAX = 10
POST_MODE_WAIT_TIME_TARGET_FOCUS_MIN = 5
POST_MODE_WAIT_TIME_TARGET_FOCUS_MAX = 10

# 贝塞尔曲线参数
BEZIER_MAX_STEPS = 50
BEZIER_MIN_STEPS = 15
BEZIER_CONTROL_POINT_VARIATION = 0.3

# 贝塞尔曲线控制点偏移（整数百分比，避免浮点运算）
BEZIER_CONTROL_OFFSET_MIN = 10  # 10% = 0.1
BEZIER_CONTROL_OFFSET_MAX = 40  # 40% = 0.4

# 模式间过渡参数
MODE_TRANSITION_MIN_STEPS = 20  # 模式过渡最小步数
MODE_TRANSITION_MAX_STEPS = 60  # 模式过渡最大步数
MODE_TRANSITION_CONTROL_OFFSET = 30  # 过渡控制点偏移 30%

# 等待时间参数（支持零等待）
ZERO_WAIT_PROBABILITY = 30  # 30% 概率使用零等待

# Perlin噪声参数
PERLIN_FREQUENCY_DEFAULT = 1.0
PERLIN_FREQUENCY_WEB_BROWSE = 2.0
PERLIN_FREQUENCY_TARGET_FOCUS = 3.0
PERLIN_FREQUENCY_CIRCULAR = 1.5
PERLIN_AMPLITUDE_SMALL = 0.5
PERLIN_AMPLITUDE_MEDIUM = 2.0
PERLIN_AMPLITUDE_LARGE = 5.0

# 风力算法参数
WIND_STRENGTH_DEFAULT = 2.0
WIND_STRENGTH_SCAN = 3.0
WIND_FREQUENCY = 0.5

# 重力算法参数
GRAVITY_STRENGTH_DEFAULT = 0.1
GRAVITY_STRENGTH_FOCUS = 0.15

# 椭圆轨迹参数
ELLIPSE_RATIO_MIN = 0.7
ELLIPSE_RATIO_MAX = 1.3

# 性能统计参数
ENABLE_PERFORMANCE_STATS = False
PERFORMANCE_REPORT_INTERVAL = 60

# 范围管理器常量
EXPLORATORY_MOVE_RANGE_MAX = 200
RANDOM_MOVE_RANGE_MAX = 150
CIRCLE_CENTER_RANGE_MAX = 600
TARGET_FOCUS_RANGE_MAX = 400

# PID 控制器参数（模拟人手调整）
PID_KP = 80  # 比例系数 (×100)
PID_KI = 5   # 积分系数 (×100)
PID_KD = 20  # 微分系数 (×100)

# 人手反应延迟（毫秒）
HUMAN_REACTION_DELAY_MIN = 100  # 最小延迟 100ms
HUMAN_REACTION_DELAY_MAX = 400  # 最大延迟 400ms

# PID 扰动参数
PID_NOISE_AMPLITUDE = 3  # 扰动幅度（细微抖动）
PID_NOISE_FREQUENCY = 500  # 扰动频率（毫秒，更平缓）

# 页面扫描速度参数（左右不对称）
SCAN_SPEED_RIGHT = 80   # 向右扫描速度 80% (慢)
SCAN_SPEED_LEFT = 140   # 向左扫描速度 140% (快)